title: Jean Broce Perez, GIT # your name (or website title) here
logo: "images/Jean_headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Hydrogeologist with a demonstrated history of working in natural resource management. Skilled in AutoCAD, Spatial Programming, Python, Geospatial Analysis, Petrophysics, and Contract Management 
  <br>
  <a href="https://www.linkedin.com/in/jean-broce-perez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
