title: Jean Broce Perez, GIT # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Hydrogeologist with a demonstrated history of working in natural resource management. Skilled in AutoCAD, ESRI products, Formation Evaluation, Petrophysics, and Contract Management 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/jean-broce-perez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
